Theoretical Questions:

 Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.

NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.



Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean(): Computes the arithmetic mean (sum of elements divided by the number of elements) of the array along the specified axis.
np.average(): Computes a weighted average. By default, it behaves like np.mean() if no weights are provided, but you can specify weights to give more importance to certain values.
Use Cases:
np.mean(): Use when you need to calculate a simple arithmetic mean of an array.

np.average(): Use when you need to compute a weighted average where certain elements of the array are more significant. This is common in situations like:

Grading systems where assignments/tests have different weights.
Financial calculations where the importance of various elements varies.

In [ ]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5])

# np.mean
mean_value = np.mean(arr)
print("Mean:", mean_value)  # Output: 3.0

# np.average without weights (same as np.mean)
avg_value = np.average(arr)
print("Average (no weights):", avg_value)  # Output: 3.0




Mean: 3.0
Average (no weights): 3.0


 Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays

In NumPy, there are several methods to reverse an array along different axes. Let's explore these methods with examples for both 1D and 2D arrays.

1. Reversing a 1D NumPy Array
For a 1D array, reversing it is equivalent to flipping the order of its elements.

Method 1: Using Slicing ([::-1])
The most straightforward way to reverse an array is using slicing.

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array using slicing
reversed_arr_1d = arr_1d[::-1]

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_arr_1d)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


Method 2: Using np.flip()
The np.flip() function reverses an array along the specified axis. For a 1D array, this flips all elements.

In [ ]:
# Reverse the array using np.flip()
reversed_arr_1d_flip = np.flip(arr_1d)

print("Reversed 1D Array using flip:", reversed_arr_1d_flip)


Reversed 1D Array using flip: [5 4 3 2 1]


2. Reversing a 2D NumPy Array
For a 2D array, you can reverse the elements along different axes (rows or columns).

Method 1: Using Slicing ([::-1])
You can reverse along different axes using slicing:

Reverse along rows (axis 0):

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows (axis 0)
reversed_arr_2d_rows = arr_2d[::-1, :]

print("Original 2D Array:\n", arr_2d)
print("Reversed along rows:\n", reversed_arr_2d_rows)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Reverse along columns (axis 1):

In [ ]:
# Reverse along columns (axis 1)
reversed_arr_2d_columns = arr_2d[:, ::-1]

print("Reversed along columns:\n", reversed_arr_2d_columns)


Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Method 2: Using np.flip()
The np.flip() function can be used to reverse along specified axes.

Reverse along rows (axis 0):

In [ ]:
# Reverse along rows using np.flip()
reversed_arr_2d_flip_rows = np.flip(arr_2d, axis=0)

print("Reversed 2D Array along rows using flip:\n", reversed_arr_2d_flip_rows)


Reversed 2D Array along rows using flip:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Reverse along columns (axis 1):

In [ ]:
# Reverse along columns using np.flip()
reversed_arr_2d_flip_columns = np.flip(arr_2d, axis=1)

print("Reversed 2D Array along columns using flip:\n", reversed_arr_2d_flip_columns)


Reversed 2D Array along columns using flip:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Conclusion
For 1D arrays, you can use slicing ([::-1]) or np.flip().
For 2D arrays, you can reverse rows, columns, or both using slicing ([::-1]) or np.flip() by specifying the axis.







 Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

. Data Types in NumPy (Importance in Memory Management and Performance)
NumPy arrays are homogeneous; all elements in the array must have the same data type. This consistency allows NumPy to manage memory more efficiently and perform faster operations, especially compared to Python's built-in lists, which can store elements of different types.

Key reasons why data types are important:
a. Memory Management:
Size of Data: Each data type (such as int, float, bool, etc.) uses a specific amount of memory. For example:
int8 takes 1 byte (8 bits) per element.
int64 takes 8 bytes (64 bits) per element.
float32 takes 4 bytes, while float64 takes 8 bytes per element.
When dealing with large arrays, using the appropriate data type can save significant amounts of memory.

In [ ]:
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)

print(arr_int8.nbytes)  # Output: 3 bytes
print(arr_int64.nbytes) # Output: 24 bytes


3
24


Efficient Storage: For large datasets, selecting a smaller data type can save memory. For example, if all the elements in an array are small integers, using int8 or int16 instead of the default int64 will result in significant memory savings.

b. Performance:
Vectorized Operations: NumPy performs vectorized operations on arrays, meaning that operations are applied to entire arrays at once rather than element by element (as is the case with Python lists). Having consistent data types allows NumPy to optimize these operations by leveraging efficient low-level routines, often written in C.

Speed of Computation: Lighter data types (like int8 or float32) allow for faster computation as they require fewer CPU cycles than heavier types (like int64 or float64). For example, a large array of 32-bit floats can be processed faster than one with 64-bit floats.

In [ ]:
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

%timeit np.sum(arr_float32)  # Faster due to smaller memory footprint
%timeit np.sum(arr_float64)  # Slower due to larger memory footprint


3.45 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.14 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


c. Type Compatibility:
Precision: Different data types have different levels of precision. For example, using float32 instead of float64 results in a loss of precision, which can be important when performing calculations that require high accuracy, such as scientific computing.

Overflow: Integer types are more prone to overflow than floating-point types. For example, an int8 data type can only represent values from -128 to 127. Exceeding this range will cause overflow.

d. Explicit Type Conversion (Casting):
You can specify or convert data types explicitly when creating or manipulating arrays to ensure efficient memory usage or compatibility with certain operations.

In [ ]:
# Specifying data type at array creation
arr = np.array([1, 2, 3], dtype=np.float32)

# Converting data type (casting)
arr_converted = arr.astype(np.int32)
print(arr_converted)  # Output: [1 2 3]


[1 2 3]


3. Summary:
Data type management is crucial in NumPy for memory efficiency and performance optimization.
Choosing the right data type based on the size and range of your data helps reduce memory usage and increase computational speed.
Ensuring the correct precision in your data types avoids errors like overflow or rounding issues during calculations.

Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

1. Definition of ndarray in NumPy
In NumPy, an ndarray (N-dimensional array) is the core data structure for working with multi-dimensional arrays. It is a homogeneous array, meaning all elements within it are of the same data type, which allows for efficient storage and computation.

Example of an ndarray:

In [ ]:
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

# Create a 2D NumPy array
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)
# Output:
# [[1 2]
#  [3 4]]


[1 2 3 4]
[[1 2]
 [3 4]]


2. Key Features of ndarray
a. Homogeneous Data:
All elements in an ndarray have the same data type (e.g., all integers, floats, etc.), which ensures efficient memory use and faster processing.

b. Multi-Dimensional:
While Python lists are typically one-dimensional (although they can be nested), ndarray can represent arrays of any number of dimensions, ranging from 1D to ND (N-dimensional).

Shape: The shape of the array is represented by a tuple, where each value corresponds to the size of the array in that dimension.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3) --> 2 rows, 3 columns


(2, 3)


c. Efficient Memory Management:
ndarray objects are stored in contiguous blocks of memory, which enables faster access and processing. This is a key advantage over Python lists, where each element can be located at a different memory address.
d. Broadcasting:
NumPy arrays support broadcasting, which allows arithmetic operations between arrays of different shapes. Instead of requiring arrays to have the same shape for operations, broadcasting automatically expands smaller arrays to match the shape of larger ones during computations.

In [ ]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[10], [20], [30]])
result = arr + arr_2d
print(result)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]


[[11 12 13]
 [21 22 23]
 [31 32 33]]


e. Vectorized Operations:
NumPy arrays allow for element-wise operations without the need for explicit loops. These vectorized operations are optimized for performance and significantly faster than manually iterating over elements in a Python list.

In [ ]:
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result = arr + arr2
print(result)  # Output: [5 7 9]


[5 7 9]


f. Mathematical and Statistical Functions:
NumPy provides a wide range of optimized mathematical and statistical functions that work efficiently on ndarray objects. Functions like np.mean(), np.sum(), np.median(), and many others are specifically designed to operate on multi-dimensional arrays with high efficiency.

In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Sum of all elements
print(np.sum(arr))  # Output: 10

# Mean of all elements
print(np.mean(arr))  # Output: 2.5


10
2.5


g. Slicing and Indexing:
NumPy arrays allow advanced indexing and slicing operations. You can extract sub-arrays, assign values, or manipulate parts of an array with ease, using powerful indexing techniques.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Slice from index 1 to 3
print(arr[1:4])  # Output: [2 3 4]

# 2D array indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[1, :])  # Output: [4 5 6]


[2 3 4]
[4 5 6]







`

### 3. **How `ndarray` Differs from Standard Python Lists**

| Feature                | `ndarray` (NumPy)                                   | Python List                                     |
|------------------------|-----------------------------------------------------|-------------------------------------------------|
| **Data Type**           | Homogeneous (all elements must be of the same type) | Heterogeneous (elements can be of different types) |
| **Memory Efficiency**   | More memory efficient due to contiguous memory      | Less memory efficient, non-contiguous memory     |
| **Performance**         | Faster due to vectorized operations and optimized C-based backend | Slower due to Python's interpreted nature and the need for explicit loops |
| **Dimensionality**      | Multi-dimensional arrays (1D, 2D, 3D, N-D)         | Can only have lists of lists for multi-dimensional structures |
| **Mathematical Operations** | Supports efficient element-wise operations, broadcasting, and advanced mathematical functions | No built-in support for element-wise operations or broadcasting |
| **Memory Storage**      | Stored in contiguous memory blocks                 | Elements are stored in separate memory locations (pointer-based) |
| **Indexing/Slicing**    | Supports advanced slicing, boolean indexing, and multidimensional indexing | Supports basic slicing and indexing, no multidimensional indexing |
| **Shape and Size**      | Has explicit `.shape` and `.size` attributes        | No built-in attributes for shape or size         |

### 4. **Summary**:
- NumPy’s `ndarray` is a powerful data structure designed for performance and efficiency, especially when working with large amounts of numerical data.
- It differs from Python lists by being homogeneous, more memory-efficient, supporting vectorized operations, broadcasting, and allowing multi-dimensional arrays.
- For mathematical computations, `ndarray` far outperforms standard Python lists in both speed and ease of use.

Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

### 1. **Performance Benefits of NumPy Arrays Over Python Lists**

When dealing with **large-scale numerical operations**, NumPy arrays (`ndarray`) offer significant performance advantages over Python lists, thanks to features like **homogeneous data storage**, **vectorized operations**, and **efficient memory management**.

#### a. **Memory Efficiency**
- **NumPy arrays** store elements of the same type (homogeneous) in **contiguous memory** blocks, which reduces memory overhead.
- **Python lists** store heterogeneous elements, which increases memory overhead as each element is an object with its own metadata (type, reference count, etc.).

#### b. **Vectorized Operations**
- **NumPy arrays** support **vectorized operations**, allowing element-wise computations without explicit loops. This leads to much faster execution because these operations are handled by **low-level C libraries** optimized for performance.
- **Python lists** require loops for element-wise operations, which adds significant overhead due to Python’s interpreted nature and slower execution.

#### c. **Broadcasting**
- **NumPy arrays** allow operations on arrays of different shapes through **broadcasting**. This flexibility reduces the need for manually reshaping arrays, which is often required in Python lists.
- **Python lists** lack broadcasting capabilities, requiring explicit loops or manual adjustments to achieve the same effect.

#### d. **Built-in Optimized Functions**
- **NumPy** provides **highly optimized mathematical and statistical functions** (e.g., `np.sum()`, `np.mean()`, `np.dot()`), all of which are implemented in low-level C or Fortran. These are far more efficient than custom implementations using Python loops.
- **Python lists** have to rely on Python’s built-in functions, which are slower and not optimized for large-scale numerical data.

#### e. **Low-Level Implementation**
- **NumPy arrays** are built on **low-level C and Fortran libraries**, giving them a significant performance advantage for numerical computations.
- **Python lists** are flexible, but their general-purpose nature makes them slower and less memory efficient for numerical tasks.

### 2. **Performance Example (Code)**

Here’s a performance comparison between NumPy arrays and Python lists for a simple large-scale numerical operation—adding two large arrays of numbers:

`

### 3. **Explanation of Results**

- **NumPy arrays** will execute significantly faster due to **vectorization** (element-wise operations handled at a low level in C). No explicit Python loops are needed.
- **Python lists**, on the other hand, require explicit loops to perform element-wise operations. This is slower because Python’s interpreter has to execute each iteration, making it less efficient for large-scale computations.

### 4. **Conclusion**

For **large-scale numerical operations**, NumPy arrays are vastly superior to Python lists in terms of both **speed** and **memory efficiency**. They are optimized for numerical tasks, offering built-in functions, vectorization, and memory management features that Python lists cannot match.

In [ ]:
import numpy as np
import time

# Define the size of the arrays
size = 10**6

# Create NumPy arrays
arr_np1 = np.arange(size)
arr_np2 = np.arange(size)

# Create Python lists
list1 = list(range(size))
list2 = list(range(size))

# Measure time for NumPy array addition
start_np = time.time()
result_np = arr_np1 + arr_np2  # Vectorized addition
end_np = time.time()
print("NumPy array addition time:", end_np - start_np)  # Expect this to be fast

# Measure time for Python list addition (element-wise)
start_list = time.time()
result_list = [x + y for x, y in zip(list1, list2)]  # Loop-based addition
end_list = time.time()
print("Python list addition time:", end_list - start_list)  # Expect this to be much slower


NumPy array addition time: 0.008609533309936523
Python list addition time: 0.14410400390625


Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

### 1. **Comparison of `vstack()` and `hstack()` Functions in NumPy**

In NumPy, both `vstack()` and `hstack()` are used for **stacking** arrays, but they operate differently in terms of how they combine arrays.

#### a. **`vstack()` (Vertical Stack)**
- **Description**: The `vstack()` function stacks arrays **vertically** (i.e., along the rows). It treats each input array as a row and stacks them on top of each other to create a larger array.
- **Dimensions**: The arrays must have the **same number of columns** (i.e., compatible in the second dimension) but can differ in the number of rows.

#### b. **`hstack()` (Horizontal Stack)**
- **Description**: The `hstack()` function stacks arrays **horizontally** (i.e., along the columns). It treats each input array as a column and stacks them side by side to create a larger array.
- **Dimensions**: The arrays must have the **same number of rows** (i.e., compatible in the first dimension) but can differ in the number of columns.



### 3. **Summary of Differences**

| Function  | Operation                          | Requirement               | Resulting Structure           |
|-----------|------------------------------------|----------------------------|--------------------------------|
| `vstack()` | Stacks arrays **vertically** (row-wise) | Same number of **columns** | Stacks arrays on top of each other (more rows) |
| `hstack()` | Stacks arrays **horizontally** (column-wise) | Same number of **rows**    | Stacks arrays side by side (more columns)       |

### 4. **When to Use**:
- **Use `vstack()`** when you want to add more rows to an existing array (i.e., stack arrays vertically).
- **Use `hstack()`** when you want to add more columns to an existing array (i.e., stack arrays horizontally).

In [ ]:
import numpy as np

# Create two 2D arrays with the same number of columns
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertically stack the arrays
result_vstack = np.vstack((arr1, arr2))
print("Result of vstack:\n", result_vstack)



Result of vstack:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np

# Create two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Horizontally stack the arrays
result_hstack = np.hstack((arr1, arr2))
print("Result of hstack:\n", result_hstack)


Result of hstack:
 [[1 2 5]
 [3 4 6]]


Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Differences Between fliplr() and flipud() in NumPy
Both fliplr() and flipud() are used to flip (reverse) arrays in NumPy, but they operate on different axes and have distinct behaviors:

1. fliplr() (Flip Left to Right)
Description: The fliplr() function flips an array horizontally (left to right). It reverses the order of elements along the columns.
Effect: For a 2D array, this function swaps the elements in each row so that the first column becomes the last, the second column becomes second to last, and so on.
Dimensionality: This function is primarily used for 2D arrays, and it requires at least 2 dimensions (number of columns > 1).
Example of fliplr():

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flip array left to right
result_fliplr = np.fliplr(arr)
print("Result of fliplr():\n", result_fliplr)


Result of fliplr():
 [[3 2 1]
 [6 5 4]]


Effect: The columns are reversed in each row, but the row order remains unchanged.

2. flipud() (Flip Up to Down)
Description: The flipud() function flips an array vertically (upside down). It reverses the order of elements along the rows.
Effect: For a 2D array, this function swaps the rows so that the first row becomes the last, the second row becomes second to last, and so on.
Dimensionality: This function works for any number of dimensions, as it operates by flipping the first axis (rows).
Example of flipud():

In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flip array upside down
result_flipud = np.flipud(arr)
print("Result of flipud():\n", result_flipud)


Result of flipud():
 [[4 5 6]
 [1 2 3]]


Effect: The rows are reversed, but the order of the elements in each row remains the same.

3. Behavior on Higher Dimensions
For 3D arrays or higher-dimensional arrays:

fliplr(): Only reverses the order of the elements along the second axis (columns).
flipud(): Only reverses the order of elements along the first axis (rows).
Example with 3D array:

In [ ]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])

# Flip left to right
result_fliplr_3d = np.fliplr(arr_3d)
print("fliplr on 3D array:\n", result_fliplr_3d)

# Flip upside down
result_flipud_3d = np.flipud(arr_3d)
print("flipud on 3D array:\n", result_flipud_3d)


fliplr on 3D array:
 [[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]
flipud on 3D array:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]



### 4. **Summary of Differences**

| Function  | Operation                | Axis Affected         | Effect on Array       |
|-----------|--------------------------|-----------------------|-----------------------|
| `fliplr()` | Flip **left to right**    | Second axis (columns) | Reverses the columns   |
| `flipud()` | Flip **up to down**       | First axis (rows)     | Reverses the rows      |

### 5. **When to Use**:
- **Use `fliplr()`** when you need to reverse the order of the columns in a 2D array.
- **Use `flipud()`** when you need to reverse the order of the rows in a 2D array.

Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

array_split() Method in NumPy
The array_split() function in NumPy is used to split an array into multiple sub-arrays. Unlike the split() function, which requires the number of splits to divide evenly, array_split() can handle uneven splits by distributing the elements across sub-arrays as evenly as possible.

1. Functionality of array_split()
Purpose: It allows you to divide an array into smaller sub-arrays.
Arguments:
array: The array you want to split.
indices_or_sections: The number of sections to divide the array into, or a list of indices where the splits should occur.
Returns: A list of sub-arrays, which may vary in size if the array cannot be split evenly.
2. Handling Uneven Splits
When the size of the array is not evenly divisible by the number of splits, array_split() distributes the remainder across the earlier sub-arrays, making them slightly larger than the rest.

Example of Uneven Split

In [ ]:
import numpy as np

# Create a 1D array with 10 elements
arr = np.arange(10)

# Split the array into 3 uneven parts
result = np.array_split(arr, 3)
print("Result of array_split into 3 parts:")
for sub_array in result:
    print(sub_array)


Result of array_split into 3 parts:
[0 1 2 3]
[4 5 6]
[7 8 9]


Explanation: The array has 10 elements, but since 10 is not evenly divisible by 3, the first sub-array has 4 elements, and the remaining two sub-arrays have 3 elements each.
3. Example of Even Split

In [ ]:
# Create a 1D array with 9 elements
arr_even = np.arange(9)

# Split the array into 3 even parts
result_even = np.array_split(arr_even, 3)
print("Result of array_split into 3 even parts:")
for sub_array in result_even:
    print(sub_array)


Result of array_split into 3 even parts:
[0 1 2]
[3 4 5]
[6 7 8]


Explanation: Here, the array has 9 elements, which can be evenly divided into 3 sub-arrays of equal size.
4. Splitting Multi-Dimensional Arrays
The array_split() method works similarly for multi-dimensional arrays, splitting along a specified axis (default is axis 0).

Example of 2D Array Split

In [ ]:
# Create a 2D array
arr_2d = np.arange(12).reshape(4, 3)

# Split the 2D array into 3 uneven parts
result_2d = np.array_split(arr_2d, 3)

print("Result of array_split on 2D array:")
for sub_array in result_2d:
    print(sub_array)


Result of array_split on 2D array:
[[0 1 2]
 [3 4 5]]
[[6 7 8]]
[[ 9 10 11]]


Explanation: The first two sub-arrays have 1 row each, and the third sub-array has 2 rows, as the split is uneven.
5. Summary of array_split()
Feature	Description
Handles Uneven Splits	Distributes extra elements across early sub-arrays
Input	Array and the number of sections or split indices
Output	List of sub-arrays (may vary in size if uneven)
Multi-Dimensional Support	Can split multi-dimensional arrays along specified axes
6. When to Use:
Use array_split() when you need to divide an array into parts and the total number of elements is not evenly divisible by the number of desired sections.







 Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


### Vectorization and Broadcasting in NumPy

**Vectorization** and **broadcasting** are key concepts in NumPy that contribute significantly to efficient array operations, making computations faster and more readable by avoiding explicit loops.

### 1. **Vectorization**

#### Concept:
- **Vectorization** refers to the process of performing operations on entire arrays (vectors) at once, rather than using explicit loops to iterate over individual elements.
- It leverages low-level optimizations and parallelism implemented in compiled libraries (like C or Fortran) to execute operations much faster than equivalent Python loops.

#### Benefits:
- **Speed**: Operations on arrays are executed in compiled code, which is typically much faster than interpreted Python loops.
- **Readability**: Code is more concise and easier to understand compared to manual looping constructs.
- **Parallelism**: Vectorized operations can take advantage of parallel processing capabilities of modern CPUs.


```
- **Explanation**: The operation `a + b` adds corresponding elements from the two arrays without explicit loops, thanks to vectorization.

### 2. **Broadcasting**

#### Concept:
- **Broadcasting** is a technique used to perform element-wise operations on arrays of different shapes. NumPy automatically adjusts the shapes of the arrays to make their dimensions compatible for element-wise operations.
- Broadcasting follows specific rules to align the dimensions of arrays before performing operations.

#### Rules of Broadcasting:
1. **If the arrays have different numbers of dimensions**, the smaller array's shape is padded with ones on the left side until both arrays have the same number of dimensions.
2. **Arrays are compatible for broadcasting** if the sizes of the dimensions are either the same or one of them is 1. If any size is different and neither is 1, broadcasting fails.
3. **Broadcasting** aligns arrays from the trailing dimensions (rightmost) towards the left. It works on the dimensions from right to left, ensuring all dimensions are compatible.


- **Explanation**: The 1D array `arr_1d` is broadcasted across the rows of `arr_2d`, so each row of `arr_2d` is added to `arr_1d` element-wise.

### 3. **Contribution to Efficient Array Operations**

#### Vectorization:
- **Performance**: Operations on whole arrays are carried out in optimized, compiled code, reducing overhead and increasing speed compared to manual loops.
- **Simplicity**: Code is more readable and concise, avoiding complex loop structures.

#### Broadcasting:
- **Flexibility**: Allows operations on arrays of different shapes without requiring explicit reshaping or replication.
- **Efficiency**: Avoids the need to create large intermediate arrays by leveraging broadcasting rules, leading to memory savings and faster execution.

### 4. **Summary**

| Concept       | Description                                               | Example Use Case                        |
|---------------|-----------------------------------------------------------|-----------------------------------------|
| **Vectorization** | Performing operations on entire arrays simultaneously | Array addition, multiplication          |
| **Broadcasting**  | Extending smaller arrays to match larger ones for element-wise operations | Adding a vector to each row of a matrix |

### 5. **When to Use**:
- **Vectorization**: Use it to perform operations on entire arrays or matrices in a more efficient and readable manner.
- **Broadcasting**: Use it to perform element-wise operations on arrays of different shapes without manual resizing or replication.

In [ ]:
import numpy as np

# Create a 2D array and a 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

# Broadcasting addition
result = arr_2d + arr_1d
print("Broadcasting addition result:\n", result)


Broadcasting addition result:
 [[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Vectorized addition
result = a + b
print("Vectorized addition result:", result)


Vectorized addition result: [ 6  8 10 12]


Practical Questions:

Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

# Generate a 3x3 array of random numbers between 0 and 1
arr1 = np.random.randint(1,101,size=(3, 3))

# Reverse the rows of the 2D array
reversed_arr_2d = arr1[::-1, :]

print("Original random array:\n", arr1)
print("Reversed 2D Array:\n", reversed_arr_2d)


Original random array:
 [[78 42 63]
 [82 63 94]
 [69 82 45]]
Reversed 2D Array:
 [[69 82 45]
 [82 63 94]
 [78 42 63]]


Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np
#Generate a 1D NumPy array with 10 elements.
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = arr1.reshape(2,5)
arr3 = arr1.reshape(5,2)
print("array arr1 is",arr1)
print("array arr2 is\n",arr2)
print("array arr3 is\n",arr3)

array arr1 is [ 1  2  3  4  5  6  7  8  9 10]
array arr2 is
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
array arr3 is
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


 Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np

# Create a 4x4 array with random floats between 0 and 1
arr1 = np.random.rand(4, 4)

# Create a 6x6 array with zeros
arr_zeros = np.zeros((6, 6))

# Extract a 4x4 slice from the 6x6 zero array
# The slice arr_zeros[1:5, 1:5] gives a 4x4 array from arr_zeros
arr_slice = arr_zeros[1:5, 1:5]

# Add the random array to the slice of zeros
resulting_array = arr_slice + arr1

print("Random array:\n", arr1)
print("Zeros array:\n", arr_zeros)
print("Resulting array:\n", resulting_array)


Random array:
 [[0.55181381 0.99196632 0.56959959 0.69351531]
 [0.2169017  0.73946586 0.15900627 0.58207036]
 [0.19688389 0.31784089 0.13878357 0.05241932]
 [0.14999212 0.11001403 0.3423288  0.37330849]]
Zeros array:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Resulting array:
 [[0.55181381 0.99196632 0.56959959 0.69351531]
 [0.2169017  0.73946586 0.15900627 0.58207036]
 [0.19688389 0.31784089 0.13878357 0.05241932]
 [0.14999212 0.11001403 0.3423288  0.37330849]]


In [ ]:
import numpy as np

# Create a 4x4 array with random float values between 0 and 1
arr = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to create a 6x6 array
# The pad_width argument specifies the number of values padded to the edges of each axis
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:\n", arr)
print("6x6 array with zero border:\n", padded_arr)


Original 4x4 array:
 [[0.24722117 0.01260514 0.45055054 0.7190227 ]
 [0.15380251 0.28578313 0.99115282 0.53764257]
 [0.9050653  0.85618251 0.3680161  0.15844176]
 [0.56333839 0.41803058 0.37890109 0.8534018 ]]
6x6 array with zero border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.24722117 0.01260514 0.45055054 0.7190227  0.        ]
 [0.         0.15380251 0.28578313 0.99115282 0.53764257 0.        ]
 [0.         0.9050653  0.85618251 0.3680161  0.15844176 0.        ]
 [0.         0.56333839 0.41803058 0.37890109 0.8534018  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np
arr = np.arange(10,60,5)
print("array of integers from 10 to 60 with a step of 5.",arr)
arr1 = np.linspace(10,60,5)
print("array of integers from 10 to 60 with a step of 5.",arr1)

array of integers from 10 to 60 with a step of 5. [10 15 20 25 30 35 40 45 50 55]
array of integers from 10 to 60 with a step of 5. [10.  22.5 35.  47.5 60. ]


Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [15]:
import numpy as np

# Create a NumPy array of strings
array_of_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array_of_strings)
lowercase_array = np.char.lower(array_of_strings)
titlecase_array = np.char.title(array_of_strings)

array_of_strings, uppercase_array, lowercase_array, titlecase_array


(array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

 Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create an array with a single string element
char_array = np.array(["Insert a space between each character of every word in the array"])

# Process the string to add spaces between each character
processed_string = ' '.join(char_array[0])

# Create a NumPy array with the processed string
result_array = np.array([processed_string])

print("Processed array:\n", result_array)


Processed array:
 ['I n s e r t   a   s p a c e   b e t w e e n   e a c h   c h a r a c t e r   o f   e v e r y   w o r d   i n   t h e   a r r a y']


 Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
# To avoid division by zero, ensure there are no zero values in array2
division_result = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise addition:\n", addition_result)
print("Element-wise subtraction:\n", subtraction_result)
print("Element-wise multiplication:\n", multiplication_result)
print("Element-wise division:\n", division_result)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np
arr1 = np.eye(5,dtype = int)
print("create a 5x5 identity matrix\n",arr1)
arr2 = arr1[arr1 >= 1]
print("extract its diagonal elements\n",arr2)


create a 5x5 identity matrix
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
extract its diagonal elements
 [1 1 1 1 1]


Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [5]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

random_integers, prime_numbers


(array([ 55, 353, 569, 321, 244, 362, 292,  88, 576, 496, 691,  94, 305,
         66, 428, 374,  98, 294, 519, 640, 378, 202, 670, 737, 396, 663,
        261, 448, 472, 656,  29, 610, 862, 659, 923, 767, 198, 842, 130,
        610, 929, 170,  69, 655, 160, 233, 777, 179,  47,  44,  14, 619,
        118, 475,  78, 800, 552, 763, 208, 671, 940, 574, 556, 971, 670,
        542, 447, 192, 131, 419, 283, 807,  52, 940,  35, 205, 844, 283,
        758, 494, 642, 369, 137,  13, 590, 488, 961, 790, 824, 349, 512,
        483, 546, 266, 277, 193, 146, 173, 721,  52]),
 [353,
  569,
  691,
  29,
  659,
  929,
  233,
  179,
  47,
  619,
  971,
  131,
  419,
  283,
  283,
  137,
  13,
  349,
  277,
  193,
  173])

Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages

In [10]:
# Daily temperatures for a month.
import numpy as np
may = np.random.randint(24,34,size=(5,7))
print("Daily temperatures for may month\n Mon Tue Web Thur Fri Sat Sun\n",may)
week1= sum[may[0][range(0,7)]]%7
week1

Daily temperatures for may month
 Mon Tue Web Thur Fri Sat Sun
 [[26 32 33 31 28 30 29]
 [24 24 24 33 33 29 24]
 [28 30 33 24 28 28 29]
 [31 27 24 24 29 27 31]
 [24 31 32 31 26 33 27]]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [14]:
import numpy as np

# Generate random temperatures between 24 and 34 for a 5-week period (5x7 matrix)
may = np.random.randint(24, 34, size=(5, 7))

print("Daily temperatures for May month\nMon Tue Wed Thur Fri Sat Sun\n", may)

# Calculate the average of the temperatures for week 1
week1 = sum(may[0])
Averageweek1 = week1/7
print("Average of temperatures for week 1:", Averageweek1)

# Calculate the average of the temperatures for week 2
week2 = sum(may[1])
Averageweek2 = week2/7
print("Average of temperatures for week 2:", Averageweek2)

# Calculate the average of the temperatures for week 3
week3 = sum(may[2])
Averageweek3 = week3/7
print("Average of temperatures for week 3:", Averageweek3)

# Calculate the average of the temperatures for week 4
week4 = sum(may[3])
Averageweek4 = week4/7
print("Average of temperatures for week 4:", Averageweek4)

# Calculate the average of the temperatures for week 5
week5 = sum(may[4])
Averageweek5 = week5/7
print("Average of temperatures for week 5:", Averageweek5)



Daily temperatures for May month
Mon Tue Wed Thur Fri Sat Sun
 [[25 30 26 33 28 29 28]
 [31 27 25 30 27 27 27]
 [31 33 26 28 29 24 31]
 [31 29 33 31 29 28 33]
 [33 30 31 30 25 29 32]]
Average of temperatures for week 1: 28.428571428571427
Average of temperatures for week 2: 27.714285714285715
Average of temperatures for week 3: 28.857142857142858
Average of temperatures for week 4: 30.571428571428573
Average of temperatures for week 5: 30.0
